### ISSUE TITLE
Documentation TODO List

### ISSUE THREAD

**Issue by Kfeavel** [Kfeavel/Panix#34]
List of all classes where documentation is needed in headers as well as in implementation files:

- [x] **Drivers**
  - [x] Driver Manager (**Only Implementation**)
  - [x] PCI (Headers & Implementation)
  - [x] Mouse (Headers & Implementation)
  - [x] Mouse Event Handler (Headers & Implementation)
  - [x] Keyboard (Headers & Implementation - **Easy Start**)
  - [x] Keyboard Event Handler (Headers & Implementation - **Easy Start**)
- [ ] LibC
  - [ ] All Libc functions (**Only Implementation**)
- [x] CPU
  - [x] Global Descriptor Table (Headers & Implementation)
  - [x] Interrupt Handler & Manager (Headers & Implementation)
  - [x] Ports (Headers & Implementation - **Needs Serious Help**)

Because we're following a tutorial series, documentation will for the most part actually be pretty easy. We just have to read the code and watch the videos and as each function is explained we re-explain it along with any changes we've made. Keep in mind that all documentation for header functions and classes should follow the Doxygen outline (A [VSCode extension](https://marketplace.visualstudio.com/items?itemName=cschlosser.doxdocgen) is available that makes this easy) and all explanations in the implementation files (.cpp & .c) should be explained with `//` and **not** `/**/` *unless the explanation begins before a function*.

**Comment by Kfeavel** [comment]
Most of the documentation is done now and available on the updated-documentation branch.

**Comment by Kfeavel** [comment]
Basically everything of importance is documented now. Haven't looked into GUI or lib stuff yet, but those are fine without major documentation. Drivers are what really needed it. Going to close and create a PR.
